# Generated by Django 3.1.2 on 2022-04-05 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 2, 30, 7, 620364)),
        ),
        migrations.AddField(
            model_name='patient',
            name='seen_by_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='wait_time',
            field=models.CharField(blank=True, default='0 min', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comorbidities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.comorbiditie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_mode',
            field=models.CharField(choices=[('T', 'T'), ('FU', 'FU'), ('FOC', 'FOC')], default='Token', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.procedure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
