# Generated by Django 3.1.2 on 2022-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220401_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
