# Generated by Django 3.1.2 on 2022-04-05 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220406_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='in_time',
            field=models.TimeField(default=datetime.time(2, 31, 23, 164672)),
        ),
    ]
