# Generated by Django 3.1.2 on 2022-03-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20220401_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedures',
            new_name='Procedure',
        ),
    ]
