# Generated by Django 3.1.2 on 2022-04-08 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20220409_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='extra_days',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='in_time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 3, 21, 2, 368734)),
        ),
    ]
