# Generated by Django 3.1.2 on 2022-03-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20220401_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
