# Generated by Django 3.1.2 on 2020-10-14 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.location')),
            ],
        ),
    ]
