# Generated by Django 3.1.2 on 2020-10-14 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('dose_given', models.CharField(default='', max_length=3000)),
                ('area_of_treatment', models.TextField(default='', max_length=3000)),
                ('cost', models.CharField(default='', max_length=2000)),
                ('result', models.TextField(default='', max_length=4000)),
                ('remark', models.TextField(default='', max_length=4000)),
                ('no_of_session', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', max_length=10)),
                ('setting1_dose', models.CharField(default='', max_length=2000, null=True)),
                ('setting2_dose', models.CharField(default='', max_length=2000, null=True)),
                ('setting3_dose', models.CharField(default='', max_length=2000, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.procedure')),
            ],
        ),
    ]
