# Generated by Django 3.1.2 on 2021-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpa_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('brndes', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rgndes', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('emp_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('outstand', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bill1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('soh', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('assdes', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('regno', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('engno', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('chsno', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('postoffice', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('road_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('city_village', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('state_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('district_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('taluk', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('office_phone_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('resi_telephone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pager_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_place', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_postoffice', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_road_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_landmark', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_city_village', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_state_des', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_district_des', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_taluk', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_pincode', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_office_phone_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_resi_telephone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gu_mobile_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cust_fatherName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('priority_tag', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('october_handling_vertical_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('acct_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pdt1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('emi_amount', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pos', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MahindraCompleteDetail',
        ),
    ]
