# Generated by Django 3.1.2 on 2020-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_procedure_procedureform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='age',
            field=models.IntegerField(),
        ),
    ]
