# Generated by Django 3.1.2 on 2020-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201014_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='no_of_session',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='procedureform',
            name='setting1_dose',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='procedureform',
            name='setting2_dose',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='procedureform',
            name='setting3_dose',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
