# Generated by Django 3.1.2 on 2020-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201023_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalentry',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
