# Generated by Django 3.1.2 on 2020-10-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20201023_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalentry',
            name='mobile_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
