# Generated by Django 3.1.2 on 2021-12-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20201023_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('final_city', models.CharField(blank=True, default='', max_length=200)),
                ('account_ref', models.CharField(blank=True, default='', max_length=200)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('registration', models.CharField(blank=True, default='', max_length=200)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('chasis_number', models.CharField(blank=True, default='', max_length=2000)),
                ('pos', models.FloatField(blank=True, default=0)),
                ('bucket', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=2000)),
                ('mobile_numer', models.CharField(blank=True, default='', max_length=12)),
                ('emi_amount', models.FloatField(blank=True, default=0)),
                ('final_emi_amount', models.FloatField(blank=True, default=0)),
                ('emi_charges', models.FloatField(blank=True, default=0)),
                ('total_overdue', models.FloatField(blank=True, default=0)),
                ('total_od_charges', models.FloatField(blank=True, default=0)),
                ('engine_number', models.CharField(blank=True, default='', max_length=500)),
                ('cm_name', models.CharField(blank=True, default='', max_length=200)),
                ('acm_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='generalentry',
            options={'verbose_name': 'General Entry', 'verbose_name_plural': 'General Entry'},
        ),
        migrations.AlterModelOptions(
            name='procedureform',
            options={'verbose_name': 'Procedure Form', 'verbose_name_plural': 'Procedure Forms'},
        ),
    ]
