# Generated by Django 3.1.2 on 2020-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20201014_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
