# Generated by Django 3.1.2 on 2020-10-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20201014_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedureform',
            old_name='setting1_dose',
            new_name='settings_dose',
        ),
        migrations.RemoveField(
            model_name='procedureform',
            name='setting2_dose',
        ),
        migrations.RemoveField(
            model_name='procedureform',
            name='setting3_dose',
        ),
    ]
