# Generated by Django 3.1.2 on 2021-12-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20211205_0242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AxisDetails',
            new_name='CompleteDetail',
        ),
    ]
