# Generated by Django 3.1.2 on 2020-10-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20201019_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedureform',
            name='no_of_session',
        ),
        migrations.RemoveField(
            model_name='procedureform',
            name='settings_dose',
        ),
        migrations.CreateModel(
            name='DoseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_session', models.IntegerField(default=0)),
                ('settings_dose', models.CharField(blank=True, default='', max_length=2000)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.procedure')),
            ],
        ),
    ]
