# Generated by Django 3.1.2 on 2020-10-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20201021_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doseupdate',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.procedureform'),
        ),
    ]
