# Generated by Django 3.1.2 on 2021-12-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20211216_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahindracompletedetail',
            name='gu_place',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
