# Generated by Django 3.1.2 on 2020-10-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20201021_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureform',
            name='no_of_session',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedureform',
            name='settings_dose',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='DoseUpdate',
        ),
    ]
