# Generated by Django 3.1.2 on 2020-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20201021_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='no_of_session',
            field=models.IntegerField(default=0),
        ),
    ]
