# Generated by Django 3.1.2 on 2021-12-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20211216_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahindracompletedetail',
            name='age',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mahindracompletedetail',
            name='bill1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mahindracompletedetail',
            name='outstand',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mahindracompletedetail',
            name='soh',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
