# Generated by Django 3.1.2 on 2021-12-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20211216_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedureform',
            name='procedure',
        ),
        migrations.DeleteModel(
            name='GeneralEntry',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='ProcedureForm',
        ),
    ]
