# Generated by Django 3.1.2 on 2020-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20201021_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='settings_dose',
            field=models.TextField(blank=True, default='', max_length=20000),
        ),
    ]
