# Generated by Django 3.1.2 on 2020-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20201021_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='mobile_number',
            field=models.IntegerField(max_length=12),
        ),
    ]
