# Generated by Django 3.1.2 on 2020-10-20 23:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20201021_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+910123456789 (country code + Mobile number)', max_length=128, region=None),
        ),
    ]
