# Generated by Django 3.1.2 on 2020-10-20 22:41

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20201021_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='mobile_number',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
