# Generated by Django 3.1.2 on 2020-10-20 22:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20201021_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureform',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
